# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false


# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT



# Mod Properties
version=1.0.0
group=me.lubanu.shieldoncrouch

# Dependencies
fabric_api_version=0.161.0+26.3
